[project]
name = "niceplace"
version = "0.1.0"
description = ""
authors = [{ name = "GregRos", email = "life.gregr@gmail.com" }]
readme = "README.md"
requires-python = ">=3.13,<3.15"
dependencies = [
    "keyweave (>=0.18.6,<0.19.0)",
    "react-tk (>=0.4.10,<0.5.0)",
    "pytest (>=8.4.2,<9.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "pyright (>=1.1.407,<2.0.0)",
    "jsonschema (>=4.25.1,<5.0.0)",
]


[tool.pytest.ini_options]
testpaths = "test"
python_classes = ["*_Test"]
python_files = ["*.py"]
[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
typeCheckingMode = "strict"
reportUnnecessaryIsInstance = false
diagnosticMode = "workspace"
reportUnusedImport = false
ignore = [
    "**/Lib/*.py",
    "**/site-packages/**",
    "**/.venv/**/*",
    "**/dist/**/*",
    "**/*.pyi",
]
exclude = ["**/site-packages/**", "**/.venv/**/*", "**/dist/**/*", "**/*.pyi"]
